#if UNITY_EDITOR && ODIN_INSPECTOR

namespace KimerA.Data.Excel.Editor
{
    using System;

    public sealed partial class ExcelEditorWindow
    {
        public static string GenerateCode(Type type)
        {
            var code = $@"// This file is auto-generated by KimerA
// do not modify this file

namespace KimerA.Data.Excel
{{
    using System;
    using System.Collections.Generic;
    using System.IO;

    
}}";


            return string.Empty;
        }
    }
}

#endif