#if UNITY_EDITOR && ODIN_INSPECTOR

namespace KimerA.Data.Excel.Editor
{
    using System.IO;
    using System.Linq;
    using KimerA.Data.Excel.Config;
    using Sirenix.OdinInspector;
    using UnityEditor;
    using UnityEditor.Compilation;

    public sealed partial class ExcelEditorWindow
    {
        [HorizontalGroup("Func")]
        [Button("Generate new structure")]
        private void GenerateNewStructure([LabelText("Structure arguments")] ExcelStructConfig config)
        {
            ExcelSetting.StructConfigs.Add(config);

            var namespaces = config.Fields
                .Where(field => field.IsStruct)
                .Select(field => GetExcelFieldNamespace(field.Type))
                .Distinct();

            var code = $@"// This file is auto-generated by KimerA
// do not modify this file

namespace {config.Namespace ?? ExcelSetting.GeneratedCodeNamespace}
{{
    using System;
    using System.Collections.Generic;
    using KimerA.Data.Excel;
    {string.Join("\n    ", namespaces.Select(ns => $"using {ns};"))}

    [Serializable]
    public struct {config.Name} : IExcelStruct
    {{
        {string.Join("\n        ", config.Fields.Select(field => $@"public {(field.IsList ? $"List<{field.Type}>" : field.Type)} {field.Name};"))}
    }}
}}
";
            var path = $"{ExcelSetting.GeneratedScriptPathRoot}/{config.Name}.g.cs";
            Utils.FileUtil.CreateFile(path);
            File.WriteAllText(path, code);
            AssetDatabase.ImportAsset(path);
            AssetDatabase.Refresh();
            CompilationPipeline.RequestScriptCompilation();
        }
    }
}

#endif